name: Deploy to Cloud Storage

on:
  push:
    branches:
      - main  # Se activa al integrar cambios en main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write' # Necesario para WIF

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Autenticación con Google Cloud usando WIF
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/863934662608/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-service-account@project-portfolio-422515.iam.gserviceaccount.com'

    # Configuración de gcloud CLI
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    # Sincronización del contenido
    - name: 'Deploy to GCS'
      run: |
        gcloud storage rsync ./app gs://[NOMBRE_DE_TU_BUCKET] --recursive --delete-unmatched-destination-objects
